-- MySQL Script generated by MySQL Workbench
-- Fri May  1 03:34:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apodo` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensajes` (
  `id` INT NOT NULL,
  `contenido` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `id` INT NOT NULL,
  `descripcion_rol` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_Rol` (
  `id` INT NOT NULL,
  `Usuario_id` INT NOT NULL,
  `Rol_id` INT NOT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `Usuario_id`, `Rol_id`),
  INDEX `fk_Usuario_has_Rol_Rol1_idx` (`Rol_id` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Rol_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Rol_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Rol_Rol1`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `mydb`.`Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permiso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `slug` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permiso_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permiso_Rol` (
  `id` INT NOT NULL,
  `permiso_id` INT NOT NULL,
  `Rol_id` INT NOT NULL,
  PRIMARY KEY (`id`, `permiso_id`, `Rol_id`),
  INDEX `fk_permiso_has_Rol_Rol1_idx` (`Rol_id` ASC) VISIBLE,
  INDEX `fk_permiso_has_Rol_permiso1_idx` (`permiso_id` ASC) VISIBLE,
  CONSTRAINT `fk_permiso_has_Rol_permiso1`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `mydb`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_has_Rol_Rol1`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `mydb`.`Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarea` (
  `id` INT NOT NULL,
  `nombre_tarea` VARCHAR(50) NULL,
  `descripcion` VARCHAR(50) NULL,
  `horas_estimadas` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_tarea` (
  `Usuario_id` INT NOT NULL,
  `tarea_id` INT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `fecha_inicio` TIMESTAMP NULL,
  `fecha_FIN` TIMESTAMP NULL,
  `estado` VARCHAR(45) NULL,
  `creado_por` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Usuario_id`),
  INDEX `fk_Usuario_tarea_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  INDEX `fk_Usuario_tarea_tarea1_idx` (`tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_tarea_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_tarea_tarea1`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `mydb`.`tarea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto` (
  `id` INT NOT NULL,
  `titulo_proyecto` VARCHAR(50) NULL,
  `descripcion` LONGTEXT NULL,
  `nombre_cliente` VARCHAR(50) NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `fecha_inicio` TIMESTAMP NULL,
  `fecha_FIN` TIMESTAMP NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyectos_tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyectos_tareas` (
  `Proyectos_id` INT NOT NULL,
  `tarea_id` INT NOT NULL,
  `horas_totales_proyecto` INT NULL,
  `proyectos_tareascol` VARCHAR(45) NULL,
  PRIMARY KEY (`Proyectos_id`, `tarea_id`),
  INDEX `fk_table1_tarea1_idx` (`tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Proyectos1`
    FOREIGN KEY (`Proyectos_id`)
    REFERENCES `mydb`.`Proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tarea1`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `mydb`.`tarea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_Proyecto` (
  `Usuario_id` INT NOT NULL,
  `Proyecto_id` INT NOT NULL,
  `asignado_por` VARCHAR(50) NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_id`, `Proyecto_id`),
  INDEX `fk_Usuario_has_Proyecto_Proyecto1_idx` (`Proyecto_id` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Proyecto_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Proyecto_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_id`)
    REFERENCES `mydb`.`Proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
